default_language_version:
  python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: ^docs/.*$
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: trailing-whitespace
        exclude: README.md
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.7
    hooks:
        - id: ruff-check
        - id: ruff-format
          args: [ --check ]
